// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreTraining.Entities.Data
{
    public partial class Role
    {
        public Role()
        {
            RoleClaims = new HashSet<RoleClaims>();
            User = new HashSet<User>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string NormalizedName { get; set; }
        public string ConcurrencyStamp { get; set; }

        public virtual ICollection<RoleClaims> RoleClaims { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}